steps:

  - label: ":habicat: Promote Release in Builder"
    command: .buildkite/scripts/promote_release_channel.sh
    agents:
      queue: habitat-release

  - block: ":habicat: Wait until Builder is stabilized"
    prompt: |
      Until we are running Builder services in leader topologies, it is
      possible that Builder can get destabilized once the Supervisor has
      been promoted to the stable channel. This should be less of an
      issue as our operations and software matures, but until then, it is
      nice to explicitly factor that into our release process

  - label: "Promote Bintray Releases"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: ":mac: Promote Homebrew Release"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Build Bootstrap Bundle and push to :s3:"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Add core/backline to Acceptance Environment"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Rebuild and promote the worker"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: ":habicat: :boom: Destroy Release Channel"
    command: .buildkite/scripts/destroy_release_channel.sh
    agents:
      queue: habitat-release

  - label: ":github: Publish Github Release"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Update Documentation"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release
