#!/bin/bash

# Obviously, this is a filthy, temporary hack
if [[ "${BUILDKITE_AGENT_META_DATA_QUEUE}" == "habitat-release" ]]; then
    echo "--- Cleaning up... removing newer hab-studios"
    sudo rm -Rf /hab/pkgs/core/hab-studio/0.57.0-dev
    sudo rm -Rf /hab/cache/artifacts/core-hab-studio-0.57.0-dev*
fi
